project 'talentora.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'talentora' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

  # Pods for talentora
  # pod 'react-native-image-crop-picker', :path => '../node_modules/react-native-image-crop-picker'
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  pod 'XCDYouTubeKit', '~> 2.5'
  
end